spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
    before: datasource-initialization

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${SECRET_KEY:FLv2CBpFozio1v8QbGG0rQ==}
    expiration: 3600000 # 1 hour in milliseconds

server:
  port: 8088

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.hibernate.SQL: DEBUG