spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  sql:
    before: datasource-initialization
    init:
      mode: always

jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${SECRET_KEY:EraMOOcjJHPTJTgB3Z/5VL4nvPe9L3bmLwgFeJnEFnQ=}
    expiration: 3600000 # 1 hour in milliseconds

server:
  port: 8099

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.quantum.authentication: DEBUG