spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
    before: datasource-initialization

## TODO: update prod yaml ddl-auto: none
jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

## TODO: Use proper secret
security:
  jwt:
    secret: ${SECRET_KEY:w6hZmYUXbmC++nZcF8L2mFJ1ZaNzfUqwvK7jR6NRY8c=}
    expiration: 3600000 # 1 hour in milliseconds

server:
  port: 8088

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.hibernate.SQL: DEBUG