spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${SECRET_KEY:defaultSecretKey123}
    expiration: 3600000 # 1 hour in milliseconds

server:
  port: 8088